### ISSUE TITLE
Quran db

### ISSUE THREAD

**Issue by AbdelrhmanUZaki** [AbdullahGhanem/quran-database#1]
السلام عليكم ورحمة الله وبركاته
ازاي حضرتك يا باشمهندس
بينما أنا أبحث عن داتابيز للقرآن عشان عايز أعمل أبليكيشن، لقيت الداتا بيز بتاعتك
https://github.com/AbdullahGhanem/quran-database?tab=readme-ov-file
جميلة ربنا يبارك لكن ينقصها حاجة واحدة.. إني أستخدمها :)
هل منها نسخة تشتغل مع sqlite أو حاجة غير mysql؟ أو حتى إني آخد جمل ال sql؟ لإن فيها جزء كبير من اللي أنا محتاجه..

شكرا

**Comment by AbdullahGhanem** [comment]
وعليكم السلام ورحمه الله وبركاته 
الحمدلله بخير اخبارك حضرتك ايه؟ 
ممكن تستخدم  tool [mysql2sqlite](https://github.com/dumblob/mysql2sqlite)
لو الموضوع منفعش معاك بردوا عرفني
الشكر لله

**Comment by AbdelrhmanUZaki** [comment]
> وعليكم السلام ورحمه الله وبركاته الحمدلله بخير اخبارك حضرتك ايه؟ ممكن تستخدم tool [mysql2sqlite](https://github.com/dumblob/mysql2sqlite) لو الموضوع منفعش معاك بردوا عرفني الشكر لله

الحمد لله في نعمة، أدام الله عليك الصحة والعافية
لا لا خلاص تمام غيرت الخطة وهتعلم mysql بدلها


لسة شغال على الداتابيز؟ عندي مشروع بوت ورد قرآني وبوت للبحث في القرآن لاستخراج مقطع صوتي بصوت شيخ معين..-لسة مبدأتش فعليا- كنت جمعت 3 apis منهم ال alquran.cloud اللي حضرتك استخدمته في الداتابيز دي و 
https://verse.mp3quran.net/arabic/
https://everyayah.com/
إجمالي كان عدد القراء 48 تقريبا، لكن مكنتش مستخدم داتابيز وكان الموضوع سيء يعني... فلو حضرتك عندك وقت تشارك مثلا أو وسيلة تواصل تبقى أسهل عشان أكيد هحتاج حد أعلم مني

**Comment by AbdelrhmanUZaki** [comment]
> وعليكم السلام ورحمه الله وبركاته الحمدلله بخير اخبارك حضرتك ايه؟ ممكن تستخدم tool [mysql2sqlite](https://github.com/dumblob/mysql2sqlite) لو الموضوع منفعش معاك بردوا عرفني الشكر لله

واي مصادر الترجمة اللي في الداتابيز؟ لو هي من alquran.cloud فهما مين أو اي يخلينا نعتمد الترجمة دي؟

**Comment by AbdelrhmanUZaki** [comment]
.
